spring.application.name=shop

# 서버 포트
server.port=8080

# =========================
# MariaDB 설정
# datasource 객체는 실제 데이터베이스 접속하고 쿼리를 전송하고 결과 받아옴
# 이 파일은 설정파일 -> 여기다가 설정하면 스프링이 구동될 때 여기를 스캔해서 datasource라는 객체를 만들어 놓음
# 개발자는 datasource라는 객체를 만들지 않고 주소가 주입받아 사용
# 이렇게 되면 객체에 대한 컨트롤 가능 = 객체를 몇 개 만들었는지 파악 가능
# 그래서 스프링은 객체를 개발자가 아닌 스프링이 관리하고 개발자는 객체의 주소만 받아서 사용 -> IOC : 제어의 역전
# 스프링에서 객체를 만들어 보관하는 장소는 컨테이너
# 개발자는 객체에 대한 설정만 하고 스프링이 만들어 놓은 객체에서 주소만 주입받는 과정을 의존성 주입이라고 함 -> DI
# 수업에 따라올 때는 객체를 만들지 않고 주입받는 방식이라고 기억하면 됨
# =========================
spring.datasource.url=jdbc:mariadb://localhost:3306/shopdb
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# =========================
# MyBatis 설정
# 퍼시스턴스 프레임워크 : 데이터베이스의 CRUD
# 매퍼로 쿼리문을 관리한다
# =========================
# 매퍼의 위치
mybatis.mapper-locations=classpath:/mappers/**/*.xml
# 매퍼가 매핑하기 위한 객체의 패키지 주소
mybatis.type-aliases-package=com.human.shop.vo
# 자바의 카멜표기법으로 쓴 변수와 데이터베이스 스네이크표기법의 컬럼을 자동으로 매핑
mybatis.configuration.map-underscore-to-camel-case=true
# logging : 로그를 남겨라
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# thymeleaf
spring.thymeleaf.cache=false